# TrainLoop Configuration
trainloop:
  data_folder: data # Relative to this config file
  host_allowlist:
    # existing providers
    - api.openai.com
    - api.anthropic.com
    - generativelanguage.googleapis.com
    - api.cohere.ai
    - api.groq.com
    - api.mistral.ai
    - api.together.xyz
    - api.endpoints.anyscale.com
    - api.perplexity.ai
    - api.deepinfra.com
    - api.replicate.com
    - api-inference.huggingface.co
    - openai.azure.com
    - bedrock.us-east-1.amazonaws.com  # duplicate for other regions as needed
    - bedrock-runtime.eu-central-1.amazonaws.com  # example region; duplicate pattern for your region
    - bedrock-agent-runtime.us-east-1.amazonaws.com  # example region; duplicate pattern for your region

  log_level: warn
  # Judge Configuration
  judge:
    env_path: "../.env.judge" # Optional: Path to a .env file to load for the judge (e.g., for API keys)
    models:
      - openai/gpt-4.1-2025-04-14
      - anthropic/claude-sonnet-4-20250514
    calls_per_model_per_claim: 3
    temperature: 0.7
  # Benchmark Configuration (optional)
  benchmark:
    providers:
      - openai/gpt-4o
      - anthropic/claude-sonnet-4-20250514
      - gemini/gemini-2.5-flash
    temperature: 0.7
    max_samples: 50  # Limit number of samples to benchmark (optional)
