trainloop:
  data_folder: data
  host_allowlist:
  - api.openai.com
  - api.anthropic.com
  log_level: warn
  judge:
    env_path: ../.env.judge
    models:
    - openai/gpt-4.1-2025-04-14
    - anthropic/claude-sonnet-4-20250514
    calls_per_model_per_claim: 3
    temperature: 0.7
  benchmark:
    providers:
    - openai/gpt-4o
    - anthropic/claude-sonnet-4-20250514
    - gemini/gemini-2.5-flash
    temperature: 0.7
    max_samples: 50
  version: 0.8.0
